"""Initial migration

Revision ID: e8f6412800f4
Revises: 
Create Date: 2026-01-13 10:16:14.792765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e8f6412800f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expeditions', 'status',
               existing_type=mysql.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('expeditions', 'status',
               existing_type=mysql.VARCHAR(length=50),
               server_default=sa.text("'draft'"),
               existing_nullable=False)
    # ### end Alembic commands ###
