"""your description

Revision ID: f53efd85673f
Revises: a1b2c3d4e5f6
Create Date: 2026-02-11 19:40:53.213646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f53efd85673f'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_page_sections_id'), table_name='page_sections')
    op.drop_index(op.f('ix_page_sections_key'), table_name='page_sections')
    op.drop_index(op.f('ix_page_sections_page'), table_name='page_sections')
    op.drop_table('page_sections')
    op.alter_column('leads', 'interest_type',
               existing_type=mysql.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('leads', 'interest_type',
               existing_type=mysql.VARCHAR(length=20),
               server_default=sa.text("'trek'"),
               existing_nullable=False)
    op.create_table('page_sections',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('page', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('subtitle', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('badge_text', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('body_html', mysql.TEXT(), nullable=True),
    sa.Column('image_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('cta_label', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cta_url', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('display_order', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_page_sections_page'), 'page_sections', ['page'], unique=False)
    op.create_index(op.f('ix_page_sections_key'), 'page_sections', ['key'], unique=False)
    op.create_index(op.f('ix_page_sections_id'), 'page_sections', ['id'], unique=False)
    # ### end Alembic commands ###
