// ============================================
// Mock Data for Development
// NOTE: In production, all user-facing pages now use live API data.
// These mocks are kept only as safe fallbacks or for local demos.
// ============================================

import type { Trek, Testimonial, Guide, Office, Expedition } from './types';

export const MOCK_TREKS: Trek[] = [
  {
    id: 1,
    name: 'Hampta Pass Trek',
    slug: 'hampta-pass',
    difficulty: 'moderate',
    duration: 5,
    price: 12999,
    best_season: ['May', 'June', 'September', 'October'],
    max_altitude: 4270,
    distance: 35,
    description: 'One of the most dramatic crossovers in the Himalayas, Hampta Pass takes you from the lush green valleys of Kullu to the barren landscapes of Lahaul.',
    short_description: 'Cross from lush Kullu valley to barren Lahaul desert in this dramatic Himalayan crossover trek.',
    featured_image: 'https://images.unsplash.com/photo-1585409677983-0f6c41ca9c3b?w=800',
    location: 'Kullu-Lahaul, Himachal Pradesh',
    status: 'published',
    group_size_min: 4,
    group_size_max: 15,
    rating: 4.8,
    review_count: 124,
    featured: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 2,
    name: 'Kedarkantha Trek',
    slug: 'kedarkantha',
    difficulty: 'easy',
    duration: 6,
    price: 9999,
    best_season: ['December', 'January', 'February', 'March'],
    max_altitude: 3810,
    distance: 20,
    description: 'Perfect winter trek with stunning snow-covered trails and panoramic views of Himalayan peaks.',
    short_description: 'A perfect winter trek with pristine snow trails and 360-degree summit views.',
    featured_image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800',
    location: 'Uttarkashi, Uttarakhand',
    status: 'published',
    group_size_min: 4,
    group_size_max: 20,
    rating: 4.9,
    review_count: 256,
    featured: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 3,
    name: 'Valley of Flowers',
    slug: 'valley-of-flowers',
    difficulty: 'moderate',
    duration: 6,
    price: 14999,
    best_season: ['July', 'August', 'September'],
    max_altitude: 3658,
    distance: 38,
    description: 'UNESCO World Heritage Site featuring over 600 species of exotic flowers blooming in the monsoon.',
    short_description: 'Walk through a UNESCO World Heritage Site carpeted with exotic Himalayan flowers.',
    featured_image: 'https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=800',
    location: 'Chamoli, Uttarakhand',
    status: 'published',
    group_size_min: 4,
    group_size_max: 16,
    rating: 4.7,
    review_count: 89,
    featured: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 4,
    name: 'Roopkund Trek',
    slug: 'roopkund',
    difficulty: 'difficult',
    duration: 8,
    price: 18999,
    best_season: ['May', 'June', 'September', 'October'],
    max_altitude: 5029,
    distance: 53,
    description: 'The mysterious skeleton lake trek - one of the most challenging and rewarding treks in India.',
    short_description: 'Trek to the mysterious skeleton lake at 5,029m - a challenging high-altitude adventure.',
    featured_image: 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=800',
    location: 'Chamoli, Uttarakhand',
    status: 'published',
    group_size_min: 4,
    group_size_max: 12,
    rating: 4.6,
    review_count: 67,
    featured: false,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 5,
    name: 'Sar Pass Trek',
    slug: 'sar-pass',
    difficulty: 'moderate',
    duration: 5,
    price: 11999,
    best_season: ['April', 'May', 'June'],
    max_altitude: 4200,
    distance: 48,
    description: 'Experience thrilling snow slides and stunning meadows on this classic Himalayan trek from Kasol.',
    short_description: 'Classic trek from Kasol featuring snow slides, alpine meadows, and stunning vistas.',
    featured_image: 'https://images.unsplash.com/photo-1483728642387-6c3bdd6c93e5?w=800',
    location: 'Kasol, Himachal Pradesh',
    status: 'published',
    group_size_min: 4,
    group_size_max: 15,
    rating: 4.5,
    review_count: 98,
    featured: false,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
  {
    id: 6,
    name: 'Brahmatal Trek',
    slug: 'brahmatal',
    difficulty: 'moderate',
    duration: 6,
    price: 10999,
    best_season: ['December', 'January', 'February', 'March'],
    max_altitude: 3425,
    distance: 24,
    description: 'A winter wonderland trek with frozen lakes and spectacular views of Mt. Trishul and Nanda Ghunti.',
    short_description: 'Winter trek featuring frozen alpine lakes and views of majestic Himalayan peaks.',
    featured_image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800',
    location: 'Chamoli, Uttarakhand',
    status: 'published',
    group_size_min: 4,
    group_size_max: 18,
    rating: 4.8,
    review_count: 112,
    featured: true,
    created_at: '2024-01-01',
    updated_at: '2024-01-01',
  },
];

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: 1,
    name: 'Priya Sharma',
    role: 'Software Engineer',
    location: 'Bangalore',
    image_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    testimonial: 'The Kedarkantha trek was absolutely magical! The guides were professional, the food was great, and the views were breathtaking. This was my first trek and I couldn\'t have asked for a better experience.',
    trek_name: 'Kedarkantha Trek',
    rating: 5,
    verified: true,
    tags: ['Great Guides', 'Amazing Views', 'Beginner Friendly'],
    helpful_count: 24,
    date: '2024-12-15',
    featured: true,
  },
  {
    id: 2,
    name: 'Rahul Verma',
    role: 'Marketing Manager',
    location: 'Mumbai',
    image_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    testimonial: 'Global Events Travels made my dream of trekking in the Himalayas come true. Their attention to safety and the beautiful campsites made this an unforgettable adventure.',
    trek_name: 'Hampta Pass Trek',
    rating: 5,
    verified: true,
    tags: ['Safety First', 'Beautiful Camps', 'Well Organized'],
    helpful_count: 18,
    date: '2024-11-20',
    featured: true,
  },
  {
    id: 3,
    name: 'Ananya Patel',
    role: 'Doctor',
    location: 'Delhi',
    image_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150',
    testimonial: 'I\'ve done multiple treks with this team and every time they exceed expectations. The Valley of Flowers was like walking through paradise. Highly recommend!',
    trek_name: 'Valley of Flowers',
    rating: 5,
    verified: true,
    tags: ['Amazing Views', 'Repeat Customer', 'Paradise'],
    helpful_count: 31,
    date: '2024-09-10',
    featured: true,
  },
  {
    id: 4,
    name: 'Vikash Kumar',
    role: 'IT Professional',
    location: 'Chennai',
    image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    testimonial: 'Did the Brahmatal trek in winter and it was surreal. Walking on frozen lakes with snow-capped peaks all around - absolutely worth it. The team ensured we were safe throughout.',
    trek_name: 'Brahmatal Trek',
    rating: 5,
    verified: true,
    tags: ['Winter Trek', 'Frozen Lakes', 'Safe'],
    helpful_count: 15,
    date: '2024-02-05',
    featured: false,
  },
  {
    id: 5,
    name: 'Sneha Reddy',
    role: 'Content Creator',
    location: 'Hyderabad',
    image_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150',
    testimonial: 'As a solo female traveler, I was initially nervous. But the team made me feel completely safe and welcome. Met amazing fellow trekkers and created memories for a lifetime!',
    trek_name: 'Kedarkantha Trek',
    rating: 4,
    verified: true,
    tags: ['Solo Friendly', 'Women Safety', 'Community'],
    helpful_count: 42,
    date: '2024-01-18',
    featured: false,
  },
  {
    id: 6,
    name: 'Arjun Nair',
    role: 'Entrepreneur',
    location: 'Kochi',
    image_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    testimonial: 'The Roopkund trek pushed my limits in the best way possible. Challenging but incredibly rewarding. The skeleton lake was eerie yet fascinating. Expert guides made all the difference.',
    trek_name: 'Roopkund Trek',
    rating: 5,
    verified: true,
    tags: ['Challenging', 'Expert Guides', 'Bucket List'],
    helpful_count: 28,
    date: '2024-10-08',
    featured: false,
  },
];

export const MOCK_GUIDES: Guide[] = [
  {
    id: 1,
    name: 'Rajesh Kumar',
    bio: 'Born and raised in the mountains of Uttarakhand, Rajesh has been leading treks for over 15 years. His deep knowledge of local terrain and culture makes every trek special.',
    experience_years: 15,
    profile_image_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300',
    specializations: ['High Altitude', 'Winter Treks', 'Photography Tours'],
    rating: 4.9,
  },
  {
    id: 2,
    name: 'Vikram Singh',
    bio: 'A certified mountaineer with experience on some of the world\'s highest peaks. Vikram brings technical expertise and a calm demeanor to challenging expeditions.',
    experience_years: 12,
    profile_image_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300',
    specializations: ['Technical Climbing', 'Expedition Leadership', 'First Aid'],
    rating: 4.8,
  },
  {
    id: 3,
    name: 'Deepa Negi',
    bio: 'One of the few female trek leaders in the region, Deepa is passionate about making trekking accessible to everyone. Her encouraging nature helps first-timers feel confident.',
    experience_years: 8,
    profile_image_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=300',
    specializations: ['Beginner Friendly', 'Women-Only Groups', 'Nature Education'],
    rating: 4.9,
  },
];

// ============================================
// Office Locations Data
// ============================================

export const OFFICES: Office[] = [
  {
    id: 1,
    name: 'Himachal Office (HQ)',
    address: "Global Camp's by Global Events Travels, Aleo road petrol pump near Chandarmaki Cottage, NSB Hotel",
    city: 'Manali',
    state: 'Himachal Pradesh',
    pincode: '175131',
    landmarks: 'Near Aleo Road Petrol Pump, NSB Hotel',
    phone: '+91 63833 13359',
    email: 'himachal@globaleventstravels.com',
    coordinates: { lat: 32.2299, lng: 77.1889 },
    mapUrl: 'https://maps.google.com/?q=32.2299,77.1889',
    image: '/images/offices/manali.jpg',
  },
  {
    id: 2,
    name: 'Chennai Office',
    address: '306, 1st Main Road, MKB Nagar',
    city: 'Chennai',
    state: 'Tamil Nadu',
    pincode: '600039',
    phone: '+91 63833 13359',
    email: 'chennai@globaleventstravels.com',
    coordinates: { lat: 13.1175, lng: 80.1434 },
    mapUrl: 'https://maps.google.com/?q=13.1175,80.1434',
    image: '/images/offices/chennai.jpg',
  },
  {
    id: 3,
    name: 'Kasol Office',
    address: "Casanova Camp's Choj Bridge, Near Bus Stand, Manikaran Road, Near Volvo",
    city: 'Kasol, Sosan',
    state: 'Himachal Pradesh',
    pincode: '175101',
    landmarks: 'Choj Bridge, Near Volvo Bus Stand',
    phone: '+91 63833 13359',
    email: 'kasol@globaleventstravels.com',
    coordinates: { lat: 32.0167, lng: 77.3167 },
    mapUrl: 'https://maps.google.com/?q=32.0167,77.3167',
    image: '/images/offices/kasol.jpg',
  },
  {
    id: 4,
    name: 'Dehradun Office',
    address: 'Kugiyal Niwas, Vimal Kumar Singh, Ganesh Vihar Lane 6, Mata Mandir Road, Near Kukreja Institute, Ajabpur Kalan',
    city: 'Dehradun',
    state: 'Uttarakhand',
    pincode: '248001',
    landmarks: 'Near Kukreja Institute, Mata Mandir Road',
    phone: '+91 63833 13359',
    email: 'dehradun@globaleventstravels.com',
    coordinates: { lat: 30.2871, lng: 78.0211 },
    mapUrl: 'https://maps.google.com/?q=30.2871,78.0211',
    image: '/images/offices/dehradun.jpg',
  },
];

// ============================================
// Expeditions Data
// ============================================

export const EXPEDITIONS: Expedition[] = [
  {
    id: 1,
    name: 'Black Peak Expedition',
    slug: 'black-peak',
    difficulty: 'expert',
    duration: 12,
    summitAltitude: 6387,
    baseAltitude: 3800,
    location: 'Gangotri, Uttarakhand',
    region: 'Garhwal Himalayas',
    description: 'Black Peak (Kalanag) is one of the most challenging and rewarding peaks in the Indian Himalayas. Standing at 6,387 meters, it offers a true mountaineering experience with technical climbing, crevasse crossings, and stunning views of the Gangotri glacier range. This expedition is perfect for experienced trekkers looking to step into high-altitude mountaineering.',
    shortDescription: 'A challenging 6,387m summit expedition in the Garhwal Himalayas with technical climbing and glacier crossings.',
    highlights: [
      'Summit at 6,387 meters - one of India\'s highest climbable peaks',
      'Technical climbing experience with rope work and ice craft',
      'Stunning views of Gangotri glacier and surrounding peaks',
      'Acclimatization at scenic high-altitude camps',
      'Certificate of achievement upon successful summit',
    ],
    requirements: {
      experience: 'Minimum 2 high-altitude treks (above 4,500m) completed',
      fitnessLevel: 'Excellent cardiovascular fitness, ability to carry 15kg pack',
      technicalSkills: ['Basic rope work', 'Crampon walking', 'Ice axe usage'],
    },
    itinerary: [
      { day: 1, title: 'Arrive Dehradun', description: 'Arrive at Dehradun. Team briefing and equipment check.', altitude: 640, activities: ['Team meeting', 'Equipment check', 'Briefing'] },
      { day: 2, title: 'Drive to Gangotri', description: 'Scenic drive along the Bhagirathi river to Gangotri.', altitude: 3048, activities: ['Drive', 'Acclimatization walk'] },
      { day: 3, title: 'Trek to Bhojwasa', description: 'Trek through beautiful pine forests to Bhojwasa.', altitude: 3792, activities: ['Trekking', 'Camping'] },
      { day: 4, title: 'Trek to Gaumukh & Tapovan', description: 'Visit Gaumukh glacier source and trek to Tapovan meadows.', altitude: 4463, activities: ['Glacier visit', 'Meadow camping'] },
      { day: 5, title: 'Acclimatization at Tapovan', description: 'Rest day for acclimatization with short hikes.', altitude: 4463, activities: ['Rest', 'Acclimatization hikes'] },
      { day: 6, title: 'Trek to Nandanvan', description: 'Trek across Gangotri glacier to Nandanvan base.', altitude: 4500, activities: ['Glacier crossing', 'Camping'] },
      { day: 7, title: 'Advance Base Camp', description: 'Establish advance base camp closer to Black Peak.', altitude: 5200, activities: ['Load ferry', 'Camp setup'] },
      { day: 8, title: 'Training Day', description: 'Technical training - rope work, crampon, ice axe.', altitude: 5200, activities: ['Technical training', 'Practice climbs'] },
      { day: 9, title: 'Summit Camp', description: 'Move to summit camp with essential gear.', altitude: 5800, activities: ['High camp', 'Rest'] },
      { day: 10, title: 'Summit Day', description: 'Early morning summit push to Black Peak (6,387m).', altitude: 6387, activities: ['Summit attempt', 'Descent to ABC'] },
      { day: 11, title: 'Descend to Tapovan', description: 'Descend back to Tapovan for celebration.', altitude: 4463, activities: ['Descent', 'Celebration'] },
      { day: 12, title: 'Return to Gangotri', description: 'Trek back to Gangotri and drive to Dehradun.', altitude: 640, activities: ['Trek', 'Drive', 'Departure'] },
    ],
    equipment: {
      provided: [
        'Mountaineering boots (if needed)',
        'Crampons and ice axe',
        'Climbing harness and helmet',
        'Ropes and carabiners',
        'High altitude tents',
        'Sleeping bags (-20°C rated)',
        'Kitchen equipment and food',
        'First aid and emergency oxygen',
      ],
      personal: [
        'Layered clothing (base, mid, outer)',
        'Down jacket',
        'Trekking poles',
        'Sunglasses and sunscreen',
        'Personal medications',
        'Headlamp with extra batteries',
        'Water bottles and hydration system',
        'Personal toiletries',
      ],
    },
    price: 65000,
    groupSize: { min: 4, max: 12 },
    season: ['May', 'June', 'September', 'October'],
    successRate: 72,
    image: '/images/expeditions/black-peak.jpg',
    gallery: [
      '/images/expeditions/black-peak-1.jpg',
      '/images/expeditions/black-peak-2.jpg',
      '/images/expeditions/black-peak-3.jpg',
    ],
    safetyInfo: 'This expedition includes trained guides, emergency oxygen, satellite communication, and evacuation protocols. All climbers must have travel insurance covering high-altitude mountaineering.',
    rating: 4.7,
    reviewCount: 23,
    featured: true,
  },
  {
    id: 2,
    name: 'Friendship Peak Expedition',
    slug: 'friendship-peak',
    difficulty: 'advanced',
    duration: 8,
    summitAltitude: 5289,
    baseAltitude: 3500,
    location: 'Manali, Himachal Pradesh',
    region: 'Pir Panjal Range',
    description: 'Friendship Peak is the perfect introduction to high-altitude mountaineering. At 5,289 meters, it offers a challenging yet achievable summit with technical sections that teach essential climbing skills. Located near Manali, it\'s easily accessible and provides stunning views of the Pir Panjal range and the Solang Valley.',
    shortDescription: 'An ideal first summit at 5,289m near Manali - perfect introduction to Himalayan mountaineering.',
    highlights: [
      'Perfect first summit for aspiring mountaineers',
      'Technical training included - ice craft and rope work',
      'Stunning 360° views from the summit',
      'Beautiful base camp at Lady Leg meadow',
      'Easy access from Manali',
      'Certificate and summit photo',
    ],
    requirements: {
      experience: 'At least one high-altitude trek (above 4,000m) recommended',
      fitnessLevel: 'Good cardiovascular fitness, regular exercise routine',
      technicalSkills: ['None required - training provided'],
    },
    itinerary: [
      { day: 1, title: 'Arrive Manali', description: 'Arrive at Manali. Team briefing at base hotel.', altitude: 2050, activities: ['Team meeting', 'Briefing', 'Gear check'] },
      { day: 2, title: 'Drive to Solang & Trek to Dhundi', description: 'Short drive to Solang, then trek to Dhundi camp.', altitude: 2850, activities: ['Drive', 'Trek', 'Camping'] },
      { day: 3, title: 'Trek to Lady Leg Base Camp', description: 'Trek through beautiful meadows to Lady Leg.', altitude: 3500, activities: ['Trekking', 'Acclimatization'] },
      { day: 4, title: 'Training Day', description: 'Technical training - crampon walking, ice axe arrest, rope techniques.', altitude: 3500, activities: ['Training', 'Practice'] },
      { day: 5, title: 'Advance Camp', description: 'Move to advance camp below the glacier.', altitude: 4200, activities: ['Trek', 'Camp setup'] },
      { day: 6, title: 'Summit Day', description: 'Early morning summit push. Return to Lady Leg.', altitude: 5289, activities: ['Summit', 'Descent', 'Celebration'] },
      { day: 7, title: 'Descend to Dhundi', description: 'Trek back to Dhundi camp.', altitude: 2850, activities: ['Descent', 'Rest'] },
      { day: 8, title: 'Return to Manali', description: 'Trek to Solang and drive back to Manali.', altitude: 2050, activities: ['Trek', 'Drive', 'Departure'] },
    ],
    equipment: {
      provided: [
        'Mountaineering boots',
        'Crampons and ice axe',
        'Climbing harness',
        'Helmet',
        'Ropes and safety gear',
        'High altitude tents',
        'Sleeping bags',
        'All meals during trek',
      ],
      personal: [
        'Warm clothing layers',
        'Down/synthetic jacket',
        'Gloves (inner and outer)',
        'Balaclava or face cover',
        'Sunglasses',
        'Sunscreen SPF 50+',
        'Personal medications',
        'Daypack',
      ],
    },
    price: 28000,
    groupSize: { min: 4, max: 15 },
    season: ['April', 'May', 'June', 'September', 'October'],
    successRate: 85,
    image: '/images/expeditions/friendship-peak.jpg',
    gallery: [
      '/images/expeditions/friendship-peak-1.jpg',
      '/images/expeditions/friendship-peak-2.jpg',
    ],
    safetyInfo: 'Includes certified guides, emergency evacuation plan, first aid kit, and weather monitoring. Suitable for fit individuals with some trekking experience.',
    rating: 4.9,
    reviewCount: 67,
    featured: true,
  },
];

// ============================================
// Utility Functions
// ============================================

// Trek utilities
export const getFeaturedTreks = () => MOCK_TREKS.filter(trek => trek.featured);
export const getTrekBySlug = (slug: string) => MOCK_TREKS.find(trek => trek.slug === slug);
export const filterTreks = (filters: {
  difficulty?: string;
  maxPrice?: number;
  season?: string;
}) => {
  return MOCK_TREKS.filter(trek => {
    if (filters.difficulty && trek.difficulty !== filters.difficulty) return false;
    if (filters.maxPrice && trek.price > filters.maxPrice) return false;
    if (filters.season && !trek.best_season.includes(filters.season)) return false;
    return true;
  });
};

// Testimonial utilities
export const getFeaturedTestimonials = () => MOCK_TESTIMONIALS.filter(t => t.featured);
export const getTestimonialsByTrek = (trekName: string) => 
  MOCK_TESTIMONIALS.filter(t => t.trek_name === trekName);

// Expedition utilities
export const getFeaturedExpeditions = () => EXPEDITIONS.filter(e => e.featured);
export const getExpeditionBySlug = (slug: string) => EXPEDITIONS.find(e => e.slug === slug);

// Office utilities
export const getOfficeByCity = (city: string) => OFFICES.find(o => o.city.toLowerCase().includes(city.toLowerCase()));

// ============================================
// Blog data is now fully dynamic via API.
// See frontend/src/lib/api.ts → blogApi
// ============================================
